# Change these first
owner: aobeid96 # Your GitHub organization or username, where this repository lives
repo: kabistatus # The name of this repository

sites:
  - name: Neom
    url: https://careers-impact.neom.com/
  - name: Samsung
    url: https://careers.samsungengineering-mena.com/
  - name: Coolinc
    url: https://careers.coolinc.com.sa/
  - name: Coolinc Staging
    url: https://coolinc.staging.hyrdd.io/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /kabistatus
  name: Kabi Systems Status
  introTitle: "Live System status"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
