# Change these first
owner: aobeid96 # Your GitHub organization or username, where this repository lives
repo: kabistatus # The name of this repository

sites:
  - name: Neom
    url: https://careers-impact.neom.com/
    icon: https://careers-impact.neom.com/api/files/download_file/settings/favicon/1/settings/favicon?1615276233
  - name: Samsung
    url: https://careers.samsungengineering-mena.com/
    icon: https://careers.samsungengineering-mena.com/api/files?fileKey=8857703_coucoucouc.JPG
  - name: Samsung API
    url: https://careers.samsungengineering-mena.com/api/health-check
    icon: https://careers.samsungengineering-mena.com/api/files?fileKey=8857703_coucoucouc.JPG
  - name: Coolinc
    url: https://careers.coolinc.com.sa/
    icon: https://careers.coolinc.com.sa/api/files?fileKey=4074801_favicon%20(2).ico
  - name: Coolinc API
    url: https://careers.coolinc.com.sa/api/health-check
    icon: https://careers.coolinc.com.sa/api/files?fileKey=4074801_favicon%20(2).ico
  - name: SNB
    url: https://career.alahlicapital.com/
    icon: https://career.alahlicapital.com/api/files?fileKey=65291_NCB2014-IOS7-MobileApp-58x58.png
  - name: SNB API
    url: https://career.alahlicapital.com/api/health-check
    icon: https://career.alahlicapital.com/api/files?fileKey=65291_NCB2014-IOS7-MobileApp-58x58.png
  - name: Flynas
    url: https://career.flynas.com/
    icon: https://career.flynas.com/api/files?fileKey=7905563_favicon.png
  - name: Flynas API
    url: https://career.flynas.com/api/health-check
    icon: https://career.flynas.com/api/files?fileKey=7905563_favicon.png
  - name: MOS
    url: https://career.mos.gov.sa/
    icon: https://career.mos.gov.sa/api/files?fileKey=7826143_favicon.png
  - name: MOS API
    url: https://career.mos.gov.sa/api/health-check
    icon: https://career.mos.gov.sa/api/files?fileKey=7826143_favicon.png
  - name: Alssef
    url: https://careers.alseef-hospital.com/
    icon: https://careers.alseef-hospital.com/api/files?fileKey=3502529_favicon.png
  - name: Alssef API
    url: https://careers.alseef-hospital.com/api/health-check
    icon: https://careers.alseef-hospital.com/api/files?fileKey=3502529_favicon.png
  - name: FTA
    url: https://fta.federaljobs.gov.ae/
    icon: https://fta.federaljobs.gov.ae/api/files?fileKey=2456650_bd68e7e9-a85f-48f2-aa4e-e381e88cd46a.png
  - name: FTA API
    url: https://fta.federaljobs.gov.ae/api/health-check
    icon: https://fta.federaljobs.gov.ae/api/files?fileKey=2456650_bd68e7e9-a85f-48f2-aa4e-e381e88cd46a.png
  - name: Ghadeer
    url: https://ghadeer.tech/
    icon: https://ghadeer.tech/api/files?fileKey=9902245_fav-ghadeer.png
  - name: Ghadeer API
    url: https://ghadeer.tech/api/health-check
    icon: https://ghadeer.tech/api/files?fileKey=9902245_fav-ghadeer.png
  - name: Marakez
    url: https://careers.marakez.net/
    icon: https://careers.marakez.net/api/files?fileKey=2147340_favico.png
  - name: Marakez API
    url: https://careers.marakez.net/api/health-check
    icon: https://careers.marakez.net/api/files?fileKey=2147340_favico.png
  - name: MLS
    url: https://careers.mls-egypt.org/
    icon: https://careers.mls-egypt.org/api/files?fileKey=236157_logo-mls.png
  - name: MLS API
    url: https://careers.mls-egypt.org/api/health-check
    icon: https://careers.mls-egypt.org/api/files?fileKey=236157_logo-mls.png
  - name: Estiqtab Cluster
    url: https://estiqtab.hyrddbh.com/
    icon: https://estiqtab.hyrddbh.com/api/files?fileKey=3010465_uae-logo.jpeg
  - name: Estiqtab Cluster API
    url: https://estiqtab.hyrddbh.com/api/health-check
    icon: https://estiqtab.hyrddbh.com/api/files?fileKey=3010465_uae-logo.jpeg
  - name: Federaljobs
    url: https://federaljobs.gov.ae/
    icon: https://federaljobs.gov.ae/api/files?fileKey=6808748_fahr-favicon.png
  - name: Federaljobs API
    url: https://federaljobs.gov.ae/api/health-check
    icon: https://federaljobs.gov.ae/api/files?fileKey=6808748_fahr-favicon.png
  - name: WizHRD
    url: https://jobs.wizhrd.co/
    icon: https://jobs.wizhrd.co/api/files?fileKey=7383629_favico.png
  - name: WizHRD API
    url: https://jobs.wizhrd.co/api/health-check
    icon: https://jobs.wizhrd.co/api/files?fileKey=7383629_favico.png
  - name: ARO
    url: https://career.aro.jeddah.hyrdd.io/
    icon: https://career.aro.jeddah.hyrdd.io/api/files?fileKey=1502401_favicon.png
  - name: ARO API
    url: https://career.aro.jeddah.hyrdd.io/api/health-check
    icon: https://career.aro.jeddah.hyrdd.io/api/files?fileKey=1502401_favicon.png
  - name: Jacrijkm
    url: https://careers.jacrijk-alrushaid.com/
    icon: https://careers.jacrijk-alrushaid.com/api/files?fileKey=4907413_logo%20jack%20rick.png
  - name: Jacrijkm API
    url: https://careers.jacrijk-alrushaid.com/api/health-check
    icon: https://careers.jacrijk-alrushaid.com/api/files?fileKey=4907413_logo%20jack%20rick.png
  - name: Esnadalriyadm
    url: https://esnadalriyadm.hyrddsa.com/
    icon: https://esnadalriyadm.hyrddsa.com/api/files?fileKey=9610987_favicon%20(1).png
  - name: Esnadalriyadm API
    url: https://esnadalriyadm.hyrddsa.com/api/health-check
    icon: https://esnadalriyadm.hyrddsa.com/api/files?fileKey=9610987_favicon%20(1).png
  - name: domty
    url: https://domty.hyrddbh.com/
    icon: https://domty.hyrddbh.com/api/files?fileKey=9162014_favicon.ico
  - name: domty API
    url: https://domty.hyrddbh.com/api/health-check
    icon: https://domty.hyrddbh.com/api/files?fileKey=9162014_favicon.ico
  - name: nits
    url: https://career.ntis.com.sa/
    icon: https://career.ntis.com.sa/api/files?fileKey=7104356_fac%20NTIS.png
  - name: nits API
    url: https://career.ntis.com.sa/api/health-check
    icon: https://career.ntis.com.sa/api/files?fileKey=7104356_fac%20NTIS.png
  - name: taqa
    url: https://taqa.hyrddsa.com/
    icon: 
  - name: taqa API
    url: https://taqa.hyrddsa.com/api/health-check
    icon: 
  - name: Ejada
    url: https://ejada.hyrddbh.com/
    icon: https://ejada.hyrddbh.com/api/files?fileKey=4413019_favicon%20(3).ico
  - name: Ejada API
    url: https://ejada.hyrddbh.com/api/health-check
    icon: https://ejada.hyrddbh.com/api/files?fileKey=4413019_favicon%20(3).ico
  - name: London
    url: https://london.hyrdd.io/
    icon: https://london.hyrdd.io/api/files?fileKey=7077379_favicon.ico
  - name: London API
    url: https://london.hyrdd.io/api/health-check
    icon: https://london.hyrdd.io/api/files?fileKey=7077379_favicon.ico
  - name: tokyo
    url: https://tokyo.hyrdd.io/
    icon: https://tokyo.hyrdd.io/api/files?fileKey=1677195_favicon.ico
  - name: tokyo API
    url: https://tokyo.hyrdd.io/api/health-check
    icon: https://tokyo.hyrdd.io/api/files?fileKey=1677195_favicon.ico
  - name: rio
    url: https://rio.hyrdd.io/
    icon: https://rio.hyrdd.io/api/files?fileKey=645986_favicon.ico
  - name: rio API
    url: https://rio.hyrdd.io/api/health-check
    icon: https://rio.hyrdd.io/api/files?fileKey=645986_favicon.ico
  - name: berlin
    url: https://berlin.hyrdd.io/
    icon: https://berlin.hyrdd.io/api/files?fileKey=1677195_favicon.ico
  - name: berlin API
    url: https://rio.hyrdd.io/api/health-check
    icon: https://berlin.hyrdd.io/api/files?fileKey=1677195_favicon.ico
  - name: tabukpharmaceuticals
    url: https://tabukpharmaceuticals.hyrddsa.com/
    icon: https://tabukpharmaceuticals.hyrddsa.com/api/files?fileKey=4641640_favicon.png
  - name: tabukpharmaceuticals API
    url: https://tabukpharmaceuticals.hyrddsa.com/api/health-check
    icon: https://tabukpharmaceuticals.hyrddsa.com/api/files?fileKey=4641640_favicon.png
  - name: Riyadhcluster
    url: https://careers.rfhc.gov.sa/
    icon: https://careers.rfhc.gov.sa/api/files?fileKey=8469213_favicon.png
  - name: Riyadhcluster API
    url: https://careers.rfhc.gov.sa/api/health-check
    icon: https://careers.rfhc.gov.sa/api/files?fileKey=8469213_favicon.png
  - name: thiqah
    url: https://careers.thiqah.sa/
    icon: https://careers.thiqah.sa/api/files?fileKey=6757047_fav-tahq.png
  - name: thiqah API
    url: https://careers.thiqah.sa/api/health-check
    icon: https://careers.thiqah.sa/api/files?fileKey=6757047_fav-tahq.png
  - name: tharwah
    url: https://careers.tharwah.net/
    icon: https://careers.tharwah.net/api/files?fileKey=1969854_62519a_76dcdff6c2af4e90b3582edf84250cfd_mv2.png
  - name: tharwah API
    url: https://careers.tharwah.net/api/health-check
    icon: https://careers.tharwah.net/api/files?fileKey=1969854_62519a_76dcdff6c2af4e90b3582edf84250cfd_mv2.png
  - name: SCISP
    url: https://careers.scisp.gov.sa/
    icon: https://careers.scisp.gov.sa/api/files?fileKey=1012024_favicon%20scisp.png
  - name: SCISP API
    url: https://careers.scisp.gov.sa/api/health-check
    icon: https://careers.scisp.gov.sa/api/files?fileKey=1012024_favicon%20scisp.png
  - name: tdf
    url: https://career.tdf.gov.sa/
    icon: https://career.tdf.gov.sa/api/files?fileKey=593220_favico.png
  - name: tdf API
    url: https://career.tdf.gov.sa/api/health-check
    icon: https://career.tdf.gov.sa/api/files?fileKey=593220_favico.png
  - name: tadawul
    url: https://tadawul.hyrddsa.com/
    icon: https://tadawul.hyrddsa.com/api/files?fileKey=6418735_favicon.ico
  - name: tadawul API
    url: https://tadawul.hyrddsa.com/api/health-check
    icon: https://tadawul.hyrddsa.com/api/files?fileKey=6418735_favicon.ico
  - name: SPARK
    url: https://career.spark.sa/
    icon: https://career.spark.sa/api/files?fileKey=2709238_logo-lan.png
  - name: SPARK API
    url: https://career.spark.sa/api/health-check
    icon: https://career.spark.sa/api/files?fileKey=2709238_logo-lan.png
  - name: Fahr
    url: https://fahr.federaljobs.gov.ae/
    icon: https://fahr.federaljobs.gov.ae/api/files?fileKey=1035833_spinner-logo.png
  - name: Fahr API
    url: https://fahr.federaljobs.gov.ae/api/health-check
    icon: https://fahr.federaljobs.gov.ae/api/files?fileKey=1035833_spinner-logo.png
  - name: TAQA
    url: https://taqa.hyrddsa.com/
    icon:
  - name: TAQA API
    url: https://taqa.hyrddsa.com/api/health-check
    icon:
  - name: Tadco
    url: https://tadco.hyrddsa.com/
    icon: https://tadco.hyrddsa.com/api/files?fileKey=3400491_logo.png
  - name: Tadco API
    url: https://tadco.hyrddsa.com/api/health-check
    icon: https://tadco.hyrddsa.com/api/files?fileKey=3400491_logo.png
  - name: SMO
    url: https://smo.hyrddsa.com/
    icon: https://smo.hyrddsa.com/api/files?fileKey=4267897_Screen%20Shot%202022-04-07%20at%208.21.53%20PM.png
  - name: SMO API
    url: https://smo.hyrddsa.com/api/health-check
    icon: https://smo.hyrddsa.com/api/files?fileKey=4267897_Screen%20Shot%202022-04-07%20at%208.21.53%20PM.png
  - name: Saudicatering 
    url: https://saudicatering.hyrddsa.com/
    icon: https://saudicatering.hyrddsa.com/api/files?fileKey=1886367_saudi-airlines-catering%20(1).png
  - name: Saudicatering  API
    url: https://saudicatering.hyrddsa.com/api/health-check
    icon: https://saudicatering.hyrddsa.com/api/files?fileKey=1886367_saudi-airlines-catering%20(1).png
  - name: Kabi 
    url: https://career.kabi.jeddah.hyrdd.io/
    icon: https://career.kabi.jeddah.hyrdd.io/api/files?fileKey=4960415_favicon.ico
  - name: Kabi API
    url: https://career.kabi.jeddah.hyrdd.io/api/health-check
    icon: https://career.kabi.jeddah.hyrdd.io/api/files?fileKey=4960415_favicon.ico
  - name: HRA
    url: https://hra.hyrddbh.com/
    icon: https://hra.hyrddbh.com/api/files?fileKey=4022944_wight.png
  - name: HRA API
    url: https://hra.hyrddbh.com/api/health-check
    icon: https://hra.hyrddbh.com/api/files?fileKey=4022944_wight.png
  - name: Mewa
    url: https://mewa.hyrddsa.com/
    icon: https://mewa.hyrddsa.com/api/files?fileKey=4344767_favicon%20(1).ico
  - name: Mewa API
    url: https://mewa.hyrddsa.com/api/health-check
    icon: https://mewa.hyrddsa.com/api/files?fileKey=4344767_favicon%20(1).ico
  - name: Tsfe
    url: https://tsfe.hyrddbh.com
    icon: https://tsfe.hyrddbh.com/api/files?fileKey=9174307_tsfefavicon2.png
  - name: Tsfe API
    url: https://tsfe.hyrddbh.com/api/health-check
    icon: https://tsfe.hyrddbh.com/api/files?fileKey=9174307_tsfefavicon2.png
  # - name: KSMC
  #   url: https://careers.ksmc.med.sa/
  #   icon:
  # - name: KSMC API
  #   url: https://careers.ksmc.med.sa/api/health-check
  #   icon:
  - name: Tkh
    url: https://tkh.hyrddbh.com
    icon: 
  - name: tkh API
    url: https://tkh.hyrddbh.com/api/health-check
    icon: 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kabi.ai
  name: Status 
  logoUrl: https://kabi.ai/images/kabi-home/logo.svg
  favicon: https://career.kabi.jeddah.hyrdd.io/api/files?fileKey=4960415_favicon.ico
  theme: night
  #baseUrl: /kabistatus
  introTitle: "Live System status"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
