# Change these first
owner: aobeid96 # Your GitHub organization or username, where this repository lives
repo: kabistatus # The name of this repository

sites:
  - name: Neom
    url: https://careers-impact.neom.com/
    icon: https://careers-impact.neom.com/api/files/download_file/settings/favicon/1/settings/favicon?1615276233
  - name: Samsung
    url: https://careers.samsungengineering-mena.com/
    icon: https://careers.samsungengineering-mena.com/api/files?fileKey=8857703_coucoucouc.JPG
  - name: Samsung API
    url: https://careers.samsungengineering-mena.com/api/health-check
    icon: https://careers.samsungengineering-mena.com/api/files?fileKey=8857703_coucoucouc.JPG
  - name: Coolinc
    url: https://careers.coolinc.com.sa/
    icon: https://careers.coolinc.com.sa/api/files?fileKey=4074801_favicon%20(2).ico
  - name: Coolinc API
    url: https://careers.coolinc.com.sa/api/health-check
    icon: https://careers.coolinc.com.sa/api/files?fileKey=4074801_favicon%20(2).ico
  - name: SNB
    url: https://career.alahlicapital.com/
    icon: https://career.alahlicapital.com/api/files?fileKey=65291_NCB2014-IOS7-MobileApp-58x58.png
  - name: SNB API
    url: https://career.alahlicapital.com/api/health-check
    icon: https://career.alahlicapital.com/api/files?fileKey=65291_NCB2014-IOS7-MobileApp-58x58.png
  - name: Flynas
    url: https://career.flynas.com/
    icon: https://career.flynas.com/api/files?fileKey=7905563_favicon.png
  - name: Flynas API
    url: https://career.flynas.com/api/health-check
    icon: https://career.flynas.com/api/files?fileKey=7905563_favicon.png
  - name: MOS
    url: https://career.mos.gov.sa/
    icon: https://career.mos.gov.sa/api/files?fileKey=7826143_favicon.png
  - name: MOS API
    url: https://career.mos.gov.sa/api/health-check
    icon: https://career.mos.gov.sa/api/files?fileKey=7826143_favicon.png
  - name: alssef
    url: https://careers.alseef-hospital.com/
    icon: https://careers.alseef-hospital.com/api/files?fileKey=3502529_favicon.png
  - name: alssef API
    url: https://careers.alseef-hospital.com/api/health-check
    icon: https://careers.alseef-hospital.com/api/files?fileKey=3502529_favicon.png
  - name: FTA 
    url: https://career.fta.prod.hyrdd.io/
    icon: https://career.fta.prod.hyrdd.io/api/files?fileKey=3026925_Group 33957.png
  - name: FTA API
    url: https://career.fta.prod.hyrdd.io/api/health-check
    icon: https://career.fta.prod.hyrdd.io/api/files?fileKey=3026925_Group 33957.png
  - name: Ghadeer
    url: https://ghadeer.tech/
    icon: https://ghadeer.tech/api/files?fileKey=9902245_fav-ghadeer.png
  - name: Ghadeer API
    url: https://ghadeer.tech/api/health-check
    icon: https://ghadeer.tech/api/files?fileKey=9902245_fav-ghadeer.png
  - name: Marakez
    url: https://careers.marakez.net/
    icon: https://careers.marakez.net/api/files?fileKey=2147340_favico.png
  - name: Marakez API
    url: https://careers.marakez.net/api/health-check
    icon: https://careers.marakez.net/api/files?fileKey=2147340_favico.png
  - name: MLS
    url: https://careers.mls-egypt.org/
    icon: https://careers.mls-egypt.org/api/files?fileKey=236157_logo-mls.png
  - name: MLS API
    url: https://careers.mls-egypt.org/api/health-check
    icon: https://careers.mls-egypt.org/api/files?fileKey=236157_logo-mls.png
  - name: Estiqtab
    url: https://estiqtab.hyrddbh.com/
    icon: https://estiqtab.hyrddbh.com/api/files?fileKey=3010465_uae-logo.jpeg
  - name: Estiqtab API
    url: https://estiqtab.hyrddbh.com/api/health-check
    icon: https://estiqtab.hyrddbh.com/api/files?fileKey=3010465_uae-logo.jpeg
  - name: WizHRD
    url: https://jobs.wizhrd.co/
    icon: https://jobs.wizhrd.co/api/files?fileKey=7383629_favico.png
  - name: WizHRD API
    url: https://jobs.wizhrd.co/api/health-check
    icon: https://jobs.wizhrd.co/api/files?fileKey=7383629_favico.png
  - name: ARO
    url: https://career.aro.jeddah.hyrdd.io/
    icon: https://career.aro.jeddah.hyrdd.io/api/files?fileKey=1502401_favicon.png
  - name: ARO API
    url: https://career.aro.jeddah.hyrdd.io/api/health-check
    icon: https://career.aro.jeddah.hyrdd.io/api/files?fileKey=1502401_favicon.png
  - name: Jacrijkm
    url: https://careers.jacrijk-alrushaid.com/
    icon: https://careers.jacrijk-alrushaid.com/api/files?fileKey=4907413_logo%20jack%20rick.png
  - name: Jacrijkm API
    url: https://careers.jacrijk-alrushaid.com/api/health-check
    icon: https://careers.jacrijk-alrushaid.com/api/files?fileKey=4907413_logo%20jack%20rick.png
  - name: Esnadalriyadm
    url: https://esnadalriyadm.hyrddsa.com/
    icon: https://esnadalriyadm.hyrddsa.com/api/files?fileKey=9610987_favicon%20(1).png
  - name: Esnadalriyadm API
    url: https://esnadalriyadm.hyrddsa.com/api/health-check
    icon: https://esnadalriyadm.hyrddsa.com/api/files?fileKey=9610987_favicon%20(1).png
  - name: domty
    url: https://domty.hyrddbh.com/
    icon: https://domty.hyrddbh.com/api/files?fileKey=9162014_favicon.ico
  - name: domty API
    url: https://domty.hyrddbh.com/api/health-check
    icon: https://domty.hyrddbh.com/api/files?fileKey=9162014_favicon.ico
  - name: nits
    url: https://ntis.hyrddsa.com/
    icon: 
  - name: nits API
    url: https://ntis.hyrddsa.com/api/health-check
    icon:
  - name: taqa
    url: https://taqa.hyrddsa.com/
    icon: 
  - name: taqa API
    url: https://taqa.hyrddsa.com/api/health-check
    icon: 
  - name: london
    url: https://london.hyrdd.io/
    icon: https://london.hyrdd.io/api/files?fileKey=7077379_favicon.ico
  - name: london API
    url: https://london.hyrdd.io/api/health-check
    icon: https://london.hyrdd.io/api/files?fileKey=7077379_favicon.ico
  - name: tokyo
    url: https://tokyo.hyrdd.io/
    icon: https://tokyo.hyrdd.io/api/files?fileKey=1677195_favicon.ico
  - name: tokyo API
    url: https://tokyo.hyrdd.io/api/health-check
    icon: https://tokyo.hyrdd.io/api/files?fileKey=1677195_favicon.ico
  - name: rio
    url: https://rio.hyrdd.io/
    icon: https://rio.hyrdd.io/api/files?fileKey=645986_favicon.ico
  - name: rio API
    url: https://rio.hyrdd.io/api/health-check
    icon: https://rio.hyrdd.io/api/files?fileKey=645986_favicon.ico
  - name: berlin
    url: https://berlin.hyrdd.io/
    icon: https://berlin.hyrdd.io/api/files?fileKey=1677195_favicon.ico
  - name: berlin API
    url: https://rio.hyrdd.io/api/health-check
    icon: https://berlin.hyrdd.io/api/files?fileKey=1677195_favicon.ico
  - name: tabukpharmaceuticals
    url: https://tabukpharmaceuticals.hyrddsa.com/
    icon: https://tabukpharmaceuticals.hyrddsa.com/api/files?fileKey=4641640_favicon.png
  - name: tabukpharmaceuticals API
    url: https://tabukpharmaceuticals.hyrddsa.com/api/health-check
    icon: https://tabukpharmaceuticals.hyrddsa.com/api/files?fileKey=4641640_favicon.png
  - name: Riyadhcluster
    url: https://careers.rfhc.gov.sa/
    icon: https://careers.rfhc.gov.sa/api/files?fileKey=8469213_favicon.png
  - name: Riyadhcluster API
    url: https://careers.rfhc.gov.sa/api/health-check
    icon: https://careers.rfhc.gov.sa/api/files?fileKey=8469213_favicon.png
  - name: thiqah
    url: https://careers.thiqah.sa/
    icon: https://careers.thiqah.sa/api/files?fileKey=6757047_fav-tahq.png
  - name: thiqah API
    url: https://careers.thiqah.sa/api/health-check
    icon: https://careers.thiqah.sa/api/files?fileKey=6757047_fav-tahq.png
  - name: tharwah
    url: https://careers.tharwah.net/
    icon: https://careers.tharwah.net/api/files?fileKey=1969854_62519a_76dcdff6c2af4e90b3582edf84250cfd_mv2.png
  - name: tharwah API
    url: https://careers.tharwah.net/api/health-check
    icon: https://careers.tharwah.net/api/files?fileKey=1969854_62519a_76dcdff6c2af4e90b3582edf84250cfd_mv2.png
  - name: SCISP
    url: https://careers.scisp.gov.sa/
    icon: https://careers.scisp.gov.sa/api/files?fileKey=1012024_favicon%20scisp.png
  - name: SCISP API
    url: https://careers.scisp.gov.sa/api/health-check
    icon: https://careers.scisp.gov.sa/api/files?fileKey=1012024_favicon%20scisp.png
  - name: tdf
    url: https://career.tdf.gov.sa/
    icon: https://career.tdf.gov.sa/api/files?fileKey=593220_favico.png
  - name: tdf API
    url: https://career.tdf.gov.sa/api/health-check
    icon: https://career.tdf.gov.sa/api/files?fileKey=593220_favico.png
    
#
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: night
  baseUrl: /kabistatus
  name: Kabi Systems Status
  introTitle: "Live System status"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
